name: Auto Merge Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Ensure all checks pass before merging
      - name: Wait for checks to pass
        run: |
          PR_STATUS=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews")

          echo "PR status: $PR_STATUS"

          # If there are no reviews (empty array) or no approval, exit the workflow
          if [[ "$PR_STATUS" == "[]" ]]; then
            echo "No reviews found for this PR yet."
            exit 1
          fi

          # If there are no approved reviews, exit the workflow
          if [[ "$PR_STATUS" != *"APPROVED"* ]]; then
            echo "Pull request has not been approved"
            exit 1
          fi

      # Auto merge the pull request after checks pass
      - name: Auto merge pull request
        if: success()
        run: |
          curl -X PUT \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"commit_title": "Auto-merge PR", "merge_method": "merge"}' \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge"
